AWSTemplateFormatVersion: 2010-09-09

Description: Continuous deployment infrastructure for sample calculator application
Outputs:
  ArtifactsBucket:
    Description: S3 bucket used for artifacts
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - !Ref 'AWS::Region'
          - ArtifactsBucket
    Value: !Ref ArtifactsBucket

Resources:
  CloudFormationTrustRole:
    Description: Creating service role in IAM for AWS CloudFormation
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                  - iam:PassRole
                  - iam:DetachRolePolicy
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:DeleteRolePolicy
                  - iam:UpdateRoleDescription
                  - iam:ListRoles
                  - iam:DeleteRole
                  - iam:GetRolePolicy
                  - iam:CreateInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:GetInstanceProfile
                  - iam:ListInstanceProfiles
                  - iam:ListInstanceProfilesForRole
                  - iam:RemoveRoleFromInstanceProfile
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:iam::*:role/${AWS::StackName}*"
                  - !Sub "arn:aws:iam::*:instance-profile/${AWS::StackName}*"
              - Action:
                  - ssm:GetParameters
                  - autoscaling:*
                  - ec2:*
                  - codedeploy:*
                  - elasticloadbalancing:*
                Effect: Allow
                Resource: '*'
          PolicyName: !Join
            - '-'
            -  - !Ref 'AWS::StackName'
               - CloudFormationRolePolicy
      RoleName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CloudFormation
    Type: AWS::IAM::Role

  CodeBuildPolicy:
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          - Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
                  - /*
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'CacheBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'CacheBucket'
                  - /*
          - Action:
              - codecommit:GitPull
            Effect: Allow
            Resource:
              - !Join
                - ':'
                - - arn
                  - aws
                  - codecommit
                  - !Ref 'AWS::Region'
                  - !Ref 'AWS::AccountId'
          - Action:
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:Decrypt
            Effect: Allow
            Resource:
              - !Join
                - ':'
                - - arn:aws:kms
                  - !Ref 'AWS::Region'
                  - !Ref 'AWS::AccountId'
                  - !Join
                    - /
                    - - alias
                      - aws/s3
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicy
      Roles:
        - !Ref 'CodeBuildRole'
    Type: AWS::IAM::Policy

  CodeBuildProject:
    DependsOn:
      - CodeBuildPolicy
    Properties:
      Artifacts:
        Location: !Ref 'ArtifactsBucket'
        Name: 'build-output.zip'
        NamespaceType: BUILD_ID
        Packaging: ZIP
        Path: 'codebuild'
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: Cluster_Name
            Value: !Ref 'AWS::StackName'
      Name: !Ref 'AWS::StackName'
      ServiceRole: !Ref 'CodeBuildRole'
      Source:
        Type: GITHUB
        Location: https://github.com/sahil2311/awscodebuild.git
    Type: AWS::CodeBuild::Project

  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodeBuild
    Type: AWS::IAM::Role

  ArtifactBucketPolicy:
    Description: Setting Amazon S3 bucket policy for AWS CodePipeline access
    Properties:
      Bucket: !Ref 'ArtifactsBucket'
      PolicyDocument:
        Id: SSEAndSSLPolicy
        Statement:
          - Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketVersioning
            Condition:
              Bool:
                aws:SecureTransport: false
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt
                  - CodeBuildRole
                  - Arn
                - !GetAtt
                  - CloudFormationTrustRole
                  - Arn
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
                  - /*
            Sid: WhitelistedGet
          - Action:
              - s3:PutObject
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt
                  - CodeBuildRole
                  - Arn
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
                  - /*
            Sid: WhitelistedPut
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy

  ArtifactsBucket:
     DeletionPolicy: Delete
     Description: Creating Amazon S3 bucket for AWS CodePipeline and CodeBuild artifacts
     Properties:
       Tags:
         - Key: Name
           Value: !Join
             - '-'
             - - !Ref 'AWS::StackName'
               - ArtifactsBucket
       VersioningConfiguration:
         Status: Enabled
     Type: AWS::S3::Bucket

  CacheBucket:
     DeletionPolicy: Delete
     Description: Creating Amazon S3 bucket for CodeBuild caching
     Properties:
       Tags:
         - Key: Name
           Value: !Join
             - '-'
             - - !Ref 'AWS::StackName'
               - CacheBucket
       LifecycleConfiguration:
         Rules:
           - ExpirationInDays: 30
             Status: Enabled
     Type: AWS::S3::Bucket