AWSTemplateFormatVersion: 2010-09-09
Description: Continuous deployment infrastructure for sample calculator application

Parameters:
  AccessKey:
    Type: String
    Description: Enter your user Access Key.

  SecretKey:
    Type: String
    Description: Enter your user Secret Key.

  EKSClusterName:
    Type: String
    Default: EKS
    Description: The desired name of your AWS EKS Cluster.

  EKSVersion:
    Type: String
    Default: 1.19
    AllowedValues:
      - 1.16
      - 1.17
      - 1.18
      - 1.19
    Description: The desired version of your AWS EKS Cluster.

  EKSNodeGroupName:
    Type: String
    Default: NodeGroup01
    Description: The desired name of your AWS EKS Node Group.

  EKSDesiredWorkerNode:
    Type: Number
    Default: 2
    Description: Number of desired Worker Node.
    MinValue: 1
    MaxValue: 7

  EKSWorkerNodeInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
                    t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
                    m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
                    m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
                    c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
                    g3.8xlarge,r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
                    i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
                    d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
    ConstraintDescription: Must be a valid EC2 instance type
    Description: EC2 instance type for the node instances.

  EKSIAMRoleName:
    Type: String
    Default: EKSClusterRole
    Description: The name of the IAM role for the EKS service to assume.

  EKSKeyPair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "my-eks-key"
    Description: The name of Key Pair to etasblish connection with Worker Node.

  VpcBlock:
    Type: AWS::EC2::VPC::Id
    Description: Select existing VPC Id.

  PublicSubnet01Block:
    Type: AWS::EC2::Subnet::Id
    Description: Select your first Subnet.

  PublicSubnet02Block:
    Type: AWS::EC2::Subnet::Id
    Description: Select your second Subnet.

  AvailabilityZonePublicSubnet01:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for the Public Subnet 01.

  AvailabilityZonePublicSubnet02:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for the Public Subnet 02.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Worker Network Configuration"
        Parameters:
          - VpcBlock
          - PublicSubnet01Block
          - AvailabilityZonePublicSubnet01
          - PublicSubnet02Block
          - AvailabilityZonePublicSubnet02

      -
        Label:
          default: "EKS Cluster Information"
        Parameters:
          - EKSClusterName
          - EKSVersion
          - EKSNodeGroupName
          - EKSDesiredWorkerNode
          - EKSWorkerNodeInstanceType
          - EKSIAMRoleName
          - EKSKeyPair
          - AccessKey
          - SecretKey

Mappings:
  ServicePrincipals:
    aws-cn:
      ec2: ec2.amazonaws.com.cn
    aws-us-gov:
      ec2: ec2.amazonaws.com
    aws:
      ec2: ec2.amazonaws.com

Resources:
  CloudFormationTrustRole:
    Description: Creating service role in IAM for AWS CloudFormation
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                  - iam:PassRole
                  - iam:DetachRolePolicy
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:DeleteRolePolicy
                  - iam:UpdateRoleDescription
                  - iam:ListRoles
                  - iam:DeleteRole
                  - iam:GetRolePolicy
                  - iam:CreateInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:GetInstanceProfile
                  - iam:ListInstanceProfiles
                  - iam:ListInstanceProfilesForRole
                  - iam:RemoveRoleFromInstanceProfile
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:iam::*:role/${AWS::StackName}*"
                  - !Sub "arn:aws:iam::*:instance-profile/${AWS::StackName}*"
              - Action:
                  - ssm:GetParameters
                  - autoscaling:*
                  - ec2:*
                  - codedeploy:*
                  - elasticloadbalancing:*
                Effect: Allow
                Resource: '*'
          PolicyName: !Join
            - '-'
            -  - !Ref 'AWS::StackName'
               - CloudFormationRolePolicy
      RoleName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CloudFormation
    Type: AWS::IAM::Role

  eksVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VPC'
        - Key: Project
          Value: aws-eks

  eksInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-InternetGateway'
        - Key: Project
          Value: aws-eks

  eksVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref eksInternetGateway
      VpcId: !Ref eksVPC

  eksPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref eksVPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-RouteTable'
        - Key: Project
          Value: aws-eks

  eksPublicRoute:
    DependsOn: eksVPCGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref eksPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref eksInternetGateway

  eksPublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZonePublicSubnet01
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PublicSubnet01Block
      VpcId:
        Ref: eksVPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnet01"
        - Key: Project
          Value: aws-eks

  eksPublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZonePublicSubnet02
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PublicSubnet02Block
      VpcId:
        Ref: eksVPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnet02"
        - Key: Project
          Value: aws-eks

  eksPublicSubnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref eksPublicSubnet01
      RouteTableId: !Ref eksPublicRouteTable

  eksPublicSubnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref eksPublicSubnet02
      RouteTableId: !Ref eksPublicRouteTable

  eksSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref eksVPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SecurityGroup"
        - Key: Project
          Value: aws-eks

  eksIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref EKSIAMRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  eksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      Version: !Ref EKSVersion
      RoleArn:
        "Fn::GetAtt": [ "eksIAMRole", "Arn" ]
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref eksSecurityGroup
        SubnetIds:
          - !Ref eksPublicSubnet01
          - !Ref eksPublicSubnet02
    DependsOn: [ eksIAMRole, eksPublicSubnet01, eksPublicSubnet02, eksSecurityGroup ]

  eksNodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !FindInMap [ ServicePrincipals, !Ref "AWS::Partition", ec2 ]
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      Path: /

  eksNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSClusterName
      NodeRole:
        "Fn::GetAtt": [ "eksNodeInstanceRole", "Arn" ]
      AmiType: AL2_x86_64
      InstanceTypes:
        - !Ref EKSWorkerNodeInstanceType
      NodegroupName: !Ref EKSNodeGroupName
      RemoteAccess:
        Ec2SshKey: !Ref EKSKeyPair
      ScalingConfig:
        MinSize: 1
        DesiredSize: !Ref EKSDesiredWorkerNode
        MaxSize: 7
      Labels:
        Project: aws-eks
      Subnets:
        - !Ref eksPublicSubnet01
        - !Ref eksPublicSubnet02
    DependsOn: [ eksCluster, eksNodeInstanceRole ]

  CodeBuildPolicy:
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          - Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
                  - /*
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'CacheBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'CacheBucket'
                  - /*
          - Action:
              - codecommit:GitPull
            Effect: Allow
            Resource:
              - !Join
                - ':'
                - - arn
                  - aws
                  - codecommit
                  - !Ref 'AWS::Region'
                  - !Ref 'AWS::AccountId'
          - Action:
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:Decrypt
            Effect: Allow
            Resource:
              - !Join
                - ':'
                - - arn:aws:kms
                  - !Ref 'AWS::Region'
                  - !Ref 'AWS::AccountId'
                  - !Join
                    - /
                    - - alias
                      - aws/s3
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicy
      Roles:
        - !Ref 'CodeBuildRole'
    Type: AWS::IAM::Policy



  AccessParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/CodeBuild/AWS_ACCESS_KEY_ID"
      Type: String
      Value: !Ref AccessKey
      Description: SSM Parameter for running date command.

  SecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/CodeBuild/AWS_SECRET_ACCESS_KEY"
      Type: String
      Value: !Ref SecretKey
      Description: SSM Parameter for running date command.

  CodeBuildProject:
    DependsOn:
      - CodeBuildPolicy
    Properties:
      Artifacts:
        Location: !Ref 'ArtifactsBucket'
        Name: 'build-output.zip'
        NamespaceType: BUILD_ID
        Packaging: ZIP
        Path: 'codebuild'
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: Cluster_Name
            Value: !Ref 'EKSClusterName'
      Name: !Ref 'AWS::StackName'
      ServiceRole: !Ref 'CodeBuildRole'
      Source:
        Type: GITHUB
        Location: https://github.com/sahil2311/awscodebuild.git
    Type: AWS::CodeBuild::Project

  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodeBuild
    Type: AWS::IAM::Role

  ArtifactBucketPolicy:
    Description: Setting Amazon S3 bucket policy for AWS CodePipeline access
    Properties:
      Bucket: !Ref 'ArtifactsBucket'
      PolicyDocument:
        Id: SSEAndSSLPolicy
        Statement:
          - Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketVersioning
            Condition:
              Bool:
                aws:SecureTransport: false
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt
                  - CodeBuildRole
                  - Arn
                - !GetAtt
                  - CloudFormationTrustRole
                  - Arn
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
                  - /*
            Sid: WhitelistedGet
          - Action:
              - s3:PutObject
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt
                  - CodeBuildRole
                  - Arn
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'ArtifactsBucket'
                  - /*
            Sid: WhitelistedPut
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy

  ArtifactsBucket:
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for AWS CodePipeline and CodeBuild artifacts
    Properties:
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref 'AWS::StackName'
              - ArtifactsBucket
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket

  CacheBucket:
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for CodeBuild caching
    Properties:
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref 'AWS::StackName'
              - CacheBucket
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
    Type: AWS::S3::Bucket
Outputs:
  ArtifactsBucket:
    Description: S3 bucket used for artifacts
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - !Ref 'AWS::Region'
          - ArtifactsBucket
    Value: !Ref ArtifactsBucket
  SubnetIds:
    Description: Subnets IDs in the eksVPC
    Value: !Join [ ",", [ !Ref eksPublicSubnet01, !Ref eksPublicSubnet02 ] ]
  SecurityGroups:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Join [ ",", [ !Ref eksSecurityGroup ] ]
  VpcId:
    Description: The eksVPC Id
    Value: !Ref eksVPC